### ISSUE TITLE
Error installing League of Legends

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.phoenicis.playonlinux#2]
```
org.phoenicis.tools.http.DownloadException: Download of https://riotgamespatcher-a.akamaihd.net/ShellInstaller/BR/LeagueofLegends_BR_Installer_2016_05_13.exe has failed
	at phoenicis.tools@5.0-alpha-2/org.phoenicis.tools.http.Downloader.saveConnectionToStream(Downloader.java:241)
	at phoenicis.tools@5.0-alpha-2/org.phoenicis.tools.http.Downloader.get(Downloader.java:196)
	at phoenicis.tools@5.0-alpha-2/org.phoenicis.tools.http.Downloader.get(Downloader.java:93)
	at phoenicis.tools@5.0-alpha-2/org.phoenicis.tools.http.Downloader.get(Downloader.java:74)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$281$2701$\^eval\_$cu1$restOf.get([utils, functions, net, download]:124)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$270$1783$\^eval\_$cu1$restOf.get([utils, functions, net, resource]:101)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$253$827A$\^eval\_$cu1$restOf.run#L:22(<eval>:94)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$242$553$\^eval\_$cu1$restOf.go([engines, wine, quick_script, installer_script]:30)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$219$562$\^eval\_.run(<eval>:17)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$218$\^eval\_$cu1$restOf.:program(<eval>:124)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at phoenicis.scripts@5.0-alpha-2/org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at phoenicis.scripts@5.0-alpha-2/org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at phoenicis.scripts@5.0-alpha-2/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://riotgamespatcher-a.akamaihd.net/ShellInstaller/BR/LeagueofLegends_BR_Installer_2016_05_13.exe
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1913)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at phoenicis.tools@5.0-alpha-2/org.phoenicis.tools.http.Downloader.saveConnectionToStream(Downloader.java:214)
	... 24 more

```

**Comment by plata** [comment]
Can you verify if this is a flatpak issue? Otherwise it should be moved to scripts.

**Comment by madoar** [comment]
This is already known (see https://github.com/PhoenicisOrg/scripts/pull/797).

**Comment by plata** [comment]
Ok. Closed duplicated.

**Comment by Kreyren** [comment]
@LeandroStanger If you want to play league of legends untill it's fixed it depends on `adobeair vcrun2017` will work on wine 4.0-staging (staging is mandatory for anti-cheat).

From my POV script update only needs fixing https://github.com/PhoenicisOrg/scripts/issues/841 and it can be pushed as platinum.

doesn't work with DXVK nor PBA, probably needs to be staged, but it reaches 170FPS on AMD7870 anyway..
